apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-dev

resources:
  - ../../base

namePrefix: dev-

patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: dev-base-vm-disk
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 4096M
      - op: replace
        path: /spec/running
        value: true
    target:
      kind: VirtualMachine
