apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: base-vm-disk
  namespace: demo-base
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: base-vm-import-source
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 30Gi
